# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: MyAgentCI

parameters:
  - name: ScanningRequired
    displayName: Scanning Required?
    type: string
    values:
      - true
      - false

variables:
   workDir: '$()'

jobs:
  - job: TerraformInitFmtValidate
    displayName: Terraform Init, Fmt, Validate job
    steps:
      - task: CmdLine@2
        inputs:
          script: 'echo Hello world'

  - job: TerraformInitPlan
    displayName: Terraform Init and Plan
    
      
